package com.scenemaxeng.compiler;

import java.util.HashMap;

public class InputMapping {

    static final int KEY_UNKNOWN = 0;
    static final int KEY_ESCAPE = 1;
    static final int KEY_1 = 2;
    static final int KEY_2 = 3;
    static final int KEY_3 = 4;
    static final int KEY_4 = 5;
    static final int KEY_5 = 6;
    static final int KEY_6 = 7;
    static final int KEY_7 = 8;
    static final int KEY_8 = 9;
    static final int KEY_9 = 10;
    static final int KEY_0 = 11;
    static final int KEY_MINUS = 12;
    static final int KEY_EQUALS = 13;
    static final int KEY_BACK = 14;
    static final int KEY_TAB = 15;
    static final int KEY_Q = 16;
    static final int KEY_W = 17;
    static final int KEY_E = 18;
    static final int KEY_R = 19;
    static final int KEY_T = 20;
    static final int KEY_Y = 21;
    static final int KEY_U = 22;
    static final int KEY_I = 23;
    static final int KEY_O = 24;
    static final int KEY_P = 25;
    static final int KEY_LBRACKET = 26;
    static final int KEY_RBRACKET = 27;
    static final int KEY_RETURN = 28;
    static final int KEY_LCONTROL = 29;
    static final int KEY_A = 30;
    static final int KEY_S = 31;
    static final int KEY_D = 32;
    static final int KEY_F = 33;
    static final int KEY_G = 34;
    static final int KEY_H = 35;
    static final int KEY_J = 36;
    static final int KEY_K = 37;
    static final int KEY_L = 38;
    static final int KEY_SEMICOLON = 39;
    static final int KEY_APOSTROPHE = 40;
    static final int KEY_GRAVE = 41;
    static final int KEY_LSHIFT = 42;
    static final int KEY_BACKSLASH = 43;
    static final int KEY_Z = 44;
    static final int KEY_X = 45;
    static final int KEY_C = 46;
    static final int KEY_V = 47;
    static final int KEY_B = 48;
    static final int KEY_N = 49;
    static final int KEY_M = 50;
    static final int KEY_COMMA = 51;
    static final int KEY_PERIOD = 52;
    static final int KEY_SLASH = 53;
    static final int KEY_RSHIFT = 54;
    static final int KEY_MULTIPLY = 55;
    static final int KEY_LMENU = 56;
    static final int KEY_SPACE = 57;
    static final int KEY_CAPITAL = 58;
    static final int KEY_F1 = 59;
    static final int KEY_F2 = 60;
    static final int KEY_F3 = 61;
    static final int KEY_F4 = 62;
    static final int KEY_F5 = 63;
    static final int KEY_F6 = 64;
    static final int KEY_F7 = 65;
    static final int KEY_F8 = 66;
    static final int KEY_F9 = 67;
    static final int KEY_F10 = 68;
    static final int KEY_NUMLOCK = 69;
    static final int KEY_SCROLL = 70;
    static final int KEY_NUMPAD7 = 71;
    static final int KEY_NUMPAD8 = 72;
    static final int KEY_NUMPAD9 = 73;
    static final int KEY_SUBTRACT = 74;
    static final int KEY_NUMPAD4 = 75;
    static final int KEY_NUMPAD5 = 76;
    static final int KEY_NUMPAD6 = 77;
    static final int KEY_ADD = 78;
    static final int KEY_NUMPAD1 = 79;
    static final int KEY_NUMPAD2 = 80;
    static final int KEY_NUMPAD3 = 81;
    static final int KEY_NUMPAD0 = 82;
    static final int KEY_DECIMAL = 83;
    static final int KEY_F11 = 87;
    static final int KEY_F12 = 88;
    static final int KEY_F13 = 100;
    static final int KEY_F14 = 101;
    static final int KEY_F15 = 102;
    static final int KEY_KANA = 112;
    static final int KEY_CONVERT = 121;
    static final int KEY_NOCONVERT = 123;
    static final int KEY_YEN = 125;
    static final int KEY_NUMPADEQUALS = 141;
    static final int KEY_CIRCUMFLEX = 144;
    static final int KEY_AT = 145;
    static final int KEY_COLON = 146;
    static final int KEY_UNDERLINE = 147;
    static final int KEY_KANJI = 148;
    static final int KEY_STOP = 149;
    static final int KEY_AX = 150;
    static final int KEY_UNLABELED = 151;
    static final int KEY_PRTSCR = 154;
    static final int KEY_NUMPADENTER = 156;
    static final int KEY_RCONTROL = 157;
    static final int KEY_NUMPADCOMMA = 179;
    static final int KEY_DIVIDE = 181;
    static final int KEY_SYSRQ = 183;
    static final int KEY_RMENU = 184;
    static final int KEY_PAUSE = 197;
    static final int KEY_HOME = 199;
    static final int KEY_UP = 200;
    static final int KEY_PRIOR = 201;
    static final int KEY_PGUP = 201;
    static final int KEY_LEFT = 203;
    static final int KEY_RIGHT = 205;
    static final int KEY_END = 207;
    static final int KEY_DOWN = 208;
    static final int KEY_NEXT = 209;
    static final int KEY_PGDN = 209;
    static final int KEY_INSERT = 210;
    static final int KEY_DELETE = 211;
    static final int KEY_LMETA = 219;
    static final int KEY_RMETA = 220;
    static final int KEY_APPS = 221;
    static final int KEY_POWER = 222;
    static final int KEY_SLEEP = 223;
    static final int KEY_LAST = 224;

    HashMap<String,Integer> keyMapping = new HashMap<>();

    public InputMapping() {

        keyMapping.put("a",KEY_A);
        keyMapping.put("b",KEY_B);
        keyMapping.put("c",KEY_C);
        keyMapping.put("d",KEY_D);
        keyMapping.put("e",KEY_E);
        keyMapping.put("f",KEY_F);
        keyMapping.put("g",KEY_G);
        keyMapping.put("h",KEY_H);
        keyMapping.put("i",KEY_I);
        keyMapping.put("j",KEY_J);
        keyMapping.put("k",KEY_K);
        keyMapping.put("l",KEY_L);
        keyMapping.put("m",KEY_M);
        keyMapping.put("n",KEY_N);
        keyMapping.put("o",KEY_O);
        keyMapping.put("p",KEY_P);
        keyMapping.put("q",KEY_Q);
        keyMapping.put("r",KEY_R);
        keyMapping.put("s",KEY_S);
        keyMapping.put("t",KEY_T);
        keyMapping.put("u",KEY_U);
        keyMapping.put("v",KEY_V);
        keyMapping.put("w",KEY_W);
        keyMapping.put("x",KEY_X);
        keyMapping.put("y",KEY_Y);
        keyMapping.put("z",KEY_Z);
        keyMapping.put("up",KEY_UP);
        keyMapping.put("down",KEY_DOWN);
        keyMapping.put("left",KEY_LEFT);
        keyMapping.put("right",KEY_RIGHT);
        keyMapping.put("space",KEY_SPACE);

        keyMapping.put("0",KEY_0);
        keyMapping.put("1",KEY_1);
        keyMapping.put("2",KEY_2);
        keyMapping.put("3",KEY_3);
        keyMapping.put("4",KEY_4);
        keyMapping.put("5",KEY_5);
        keyMapping.put("6",KEY_6);
        keyMapping.put("7",KEY_7);
        keyMapping.put("8",KEY_8);
        keyMapping.put("9",KEY_9);

        keyMapping.put("del",KEY_DELETE);

    }

    public int getKeyVal(String keyName) {
        keyName=keyName.toLowerCase().replace("key ","");
        int keyVal = keyMapping.get(keyName);
        return keyVal;
    } 
}
